### ISSUE TITLE
"Cannot be deployed to environment" error because I specify a different lifecycle for the channel

### ISSUE THREAD

**Issue by mhenry1384** [OctopusDeploy/OctopusClients#111]
.\octo.exe create-release --project="$project" --channel $channel --server https://standley.channelnet.com/ --apiKey $apiKey --waitfordeployment --deployto 'QA2' --progress

>Release '20161223.002' of project 'xxxxxx' cannot be deployed to environment 'QA2' because the environment is not in the list of environments that this release can be deployed to. This may be because a) the environment does not exist, b) the name is misspelled, c) you don't have permission to deploy to this environment, or d) the environment is not in the list of environments defined by the lifecycle.

While it's true that QA2 doesn't exist in the default lifecycle, I'm deploying to a Channel that has a different lifecycle.  I think that octo.exe is not smart enough to handle this.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Cannot be deployed to environment" error because I specify a different lifecycle for the channel #111](https://trello.com/c/ONvENRat/91-cannot-be-deployed-to-environment-error-because-i-specify-a-different-lifecycle-for-the-channel-111)

**Comment by mhenry1384** [comment]
I think you need to invite me to that Trello board in order for me to see it.

**Comment by vanessalove** [comment]
@mhenry1384 the trello board is part of our private work process. The link is for us. Any relevant or public information will be provided in this issue when it needs to be shared.

By being added to the board it means its being considered to be picked up.

**Comment by droyad** [comment]
I was not able to reproduce this (`Octo 4.11.0`). I restricted the default channel to `EnvA`. My `OtherChannel` could deploy to `EnvA` and `EnvB`. I created a release for `OtherChannel` and deployed it to `EnvB`.

Also looking at the code, after the release is created, `Octo`  retrieves the deployment template, which is populated by the server with the allowed environments (same endpoint the Web UI uses).

If this is still not working for you @mhenry1384, please contact us through our support channels and send a screenshot of the channel over view page and the lifecycle overview page.
