### ISSUE TITLE
Add a --timeout option

### ISSUE THREAD

**Issue by tbolon** [OctopusDeploy/OctopusClients#112]
We are actually uploading a nupkg which is more than 40MB. It can takes more than 10 minutes depending on the load.

A --timeout option is missing on octo push, since we are limited by the ApiDefaults.cs values, which seems to be set to 10 minutes.

I can submit a PR, but I want to be sure you are interested in this feature, and that the octopus API does not have a similar timeout lock.

**Comment by droyad** [comment]
@tbolon We certainly are. The feature is on our backlog (https://github.com/OctopusDeploy/Issues/issues/2868) and we should be getting to it in the next week or so.

**Comment by tbolon** [comment]
Fixed by PR #118 thanks

Waiting for next official release.

**Comment by droyad** [comment]
@tbolon Just letting you know we have released this.
