### ISSUE TITLE
Add global.json config

### ISSUE THREAD

**Issue by tbolon** [OctopusDeploy/OctopusClients#113]
This project uses the dotnet SDK preview2 format (project.json / xproj).

To be compatible with VS 2017, it needs a global.json config file which locks the SDK used to the preview2.

See [this SO question](http://stackoverflow.com/a/40875192/8731) and [this blog post](http://www.hanselman.com/blog/PublishingASPNETCore11ApplicationsToAzureUsingGitDeploy.aspx) for details.

I will submit a PR.

**Comment by droyad** [comment]
@tbolon Thanks for that addition. I've bumped it to 1.0.0-preview2-0031**31**
