### ISSUE TITLE
Notice: AntiVirus thinks Octo.exe is a virus

### ISSUE THREAD

**Issue by Antaris** [OctopusDeploy/OctopusClients#117]
This isn't really a bug or an issue, just thought I would flag up that WebRoot SecureAnywhere classifies octo.exe as "W32.InfoStealer.Zeus"

```
An endpoint has recently detected an infection:

Infection List:
OCTO.EXE, W32.InfoStealer.Zeus, ?:\tools\new folder\,
```

If you're noticing that the exe disappears the first time you execute it, antivirus might be the cause.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notice: AntiVirus thinks Octo.exe is a virus #117](https://trello.com/c/KiMSK5za/145-notice-antivirus-thinks-octo-exe-is-a-virus-117)

**Comment by droyad** [comment]
@Antaris Thanks for the report. Do you by any chance know which version of `Octo.exe` it was?

**Comment by Antaris** [comment]
@droyad Sorry for the late reply, it was v4.5.2

**Comment by droyad** [comment]
Submitted a False Positive report to WebRoot

![image](https://cloud.githubusercontent.com/assets/1687639/22869878/50e7f450-f1ee-11e6-900d-283135a69c10.png)

**Comment by droyad** [comment]
WebRoot have recognised it as a false positive and updated their defs
