### ISSUE TITLE
Output verbosity of logger

### ISSUE THREAD

**Issue by patriksvensson** [OctopusDeploy/OctopusClients#120]
It would be nice if we could configure the Serilog log level as an argument to octo.exe.

Right now, the pack command (when adding a large directory) writes a lot of debug messages for `Adding file` which I'm not interested in.

If this is something that you think is worth having, I would glady contribute a pull request.

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Output verbosity of logger #120](https://trello.com/c/MmscOrwK/208-output-verbosity-of-logger-120)

**Comment by patriksvensson** [comment]
@droyad That wasn't meant as an answer to me right? 😆

**Comment by droyad** [comment]
@patriksvensson That's a "we'll get back to you".  Which I'll do right now.

Sounds like a good idea. It has a few wrinkles, in that the logger is created before options are parsed. Also there is (currently) no place to add that option.

I suggest adding a base class that all the commands inherit from (see `ApiCommand`, which most but not all already inherit from) and adding the option there. Then call `ConfigureLogger` again passing the log level.

**Comment by patriksvensson** [comment]
@droyad I noticed that problem when I looked at the source code yesterday. Your suggestion seems like a good one so I'll try to submit a PR within a couple of days.

Thanks for the quick reply!
