### ISSUE TITLE
Provide as a DotNetCLITool (dotnet-octo)

### ISSUE THREAD

**Issue by mariusGundersen** [OctopusDeploy/OctopusClients#155]
With the new dotnet cli there is the possibility of creating [custom cli tools](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/extensibility) for use during build. It would be great if the octopus client could be published as a simple tool, to expose for example `dotnet octo pack` and `dotnet octo push` (for pushing zip files, which nuget can't handle). 

I have experimented with the Octopus.Client nuget and a small command line program, and it works very well. It would probably be better to use the octo.exe project as a basis, so it would have the same features.

**Comment by droyad** [comment]
Interesting idea, sound like it's worth adding. The source for `Octo.exe` is also in this repo. 

It sounds like all we would need to do is build a non runtime version of `Octo` named `dotnet-octo.dll` and put it in a tools folder.

**Comment by mariusGundersen** [comment]
I've tried to do this now, just making a new project that calls `Program.Main()`, but had to upgrade the projects to vs2017, which I suspect you don't want to do just yet. I think the nuspec file needs some special attribute for it to be handled correctly. I can make a pull-request with the WIP code

**Comment by tdawgy** [comment]
It looks like the project has been migrated to vs2017, are there any plans to revisit this?

**Comment by tdawgy** [comment]
Any chance we could get this approved? It would greatly simplify some of our build processes.

**Comment by tdawgy** [comment]
If we can't get any feedback on this, should we just close it?

**Comment by YakhontovYaroslav** [comment]
This tool wont install to WSL Ubuntu 18.04 (maybe other *nix are affected too):
dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

dotnet tool install Octopus.DotNet.Cli -g

```
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'octopus.dotnet.cli' failed to install. Please contact the tool author for assistance.
```

I have found similar issue with Cake.Tool: repacking it with id 'cake-tool' (note lowercase and absence of periods) fixed the issue.

Could You please consider repacking tool with new name or should i fire a new issue?
@tdawgy

**Comment by devlead** [comment]
As I commented in issue cake-build/cake#2282, this seems more like a .NET Core Ubuntu 18.04 on WSL issue than a packaging issue.

I've tried the tool on
* Windows
* Mac
* WSL Ubuntu 16.04
* WSL openSuse Leap 42
* Docker 
  - microsoft/dotnet:2.1-sdk
  - ubuntu:18.04
  - ubuntu:16.04
  - fedora:28

**Comment by devlead** [comment]
I've raised an separate issue at dotnet/cli#9974

**Comment by hnrkndrssn** [comment]
We have released `octo.exe` as a DotNetCliTool so you can now use `dotnet octo` to get the same functionality within your build pipeline as you can from the command line, you can read more about it in this [blog post](https://octopus.com/blog/octopus-and-netcore).
