### ISSUE TITLE
Add option to all octo.exe methods to generate results as JSON or XML.

### ISSUE THREAD

**Issue by jimmcslim** [OctopusDeploy/OctopusClients#191]
It would be great if all octo.exe options (apart from export and import) supported an --outputFormat parameter to allow the results to be rendered as either JSON or XML.

**Comment by jimmcslim** [comment]
I also added a feature request on UserVoice... https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/20495281-allow-octo-exe-to-generate-results-in-machine-read

**Comment by benPearce1** [comment]
Hi James,

We have made a start on this request. 
Currently the changes are living in the https://github.com/OctopusDeploy/OctopusClients/tree/enh-cmdoutputformat branch. Feel free to provide any feedback.

In relation to the Xml output suggestion, what use-case would you see for Xml?

Regards
Ben

**Comment by jimmcslim** [comment]
None, other than it's 'enterprisey'!

There could perhaps be some legacy Windows environments where the ability to parse XML is more readily available than the ability to parse JSON?
