### ISSUE TITLE
ChannelVersionRuleResource.Actions contains Action IDs instead of Action names

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/OctopusClients#192]
[ChannelVersionRuleResource.Actions](https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Client/Model/ChannelVersionRuleResource.cs#L6) is a [ReferenceCollection](https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Client/Model/ReferenceCollection.cs#L7). This means it should only contain Ids which is not the case here as the backend expect Action names.

Was this done to avoid introducing a breaking change? Would changing the type of this collection to `HashSet`, the closest type to `ReferenceCollection`, be considered a breaking change?

Started by: https://secure.helpscout.net/conversation/416374284?folderId=557077

**Comment by pawelpabich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Action Ids instead of Names](https://trello.com/c/AuUWyQD6/716-action-ids-instead-of-names)

**Comment by droyad** [comment]
Depends on the Server version. Version 3.3.? and earlier expects IDs not names.

**Comment by pawelpabich** [comment]
Fix will be provided in the server code. https://github.com/OctopusDeploy/Issues/issues/3746
