### ISSUE TITLE
Octo.exe Latest version (4.24.0) is confused on its version

### ISSUE THREAD

**Issue by EvilTony** [OctopusDeploy/OctopusClients#198]
![image](https://user-images.githubusercontent.com/7377172/31462893-25e817e2-ae9c-11e7-9b73-25474c59e555.png)

Looks like the versioning got borked on the latest update.

**Comment by slewis74** [comment]
Another report of this here, https://help.octopusdeploy.com/discussions/problems/60372

Have confirmed it as an issue in the build process that came about with the update to Dotnet Core 2.0.

**Comment by EvilTony** [comment]
My coworker is the one who posted that problem discussion. 

There is a functional issue as well. When using 4.24.0 it is unable to create a release targeting a channel.  We had to revert back to 4.22.1 regarding it. Figured it was all fallout from bad versioning and new publishing, but still raising the issue.

**Comment by slewis74** [comment]
This was fixed in 4.24.1
