### ISSUE TITLE
Octo.exe - print URL of deployment when using --EnableServiceMessages from build

### ISSUE THREAD

**Issue by Dalmirog-zz** [OctopusDeploy/OctopusClients#206]
The goal is to print a message at the end of the deployment saying something the message below to make it easier for the TC users to see the actual deployment that was created by that build.

```
You can browse the deployment from the Octopus Portal from [https://demo.octopusdeploy.com/app#/projects/octofx/releases/3.3.2733/deployments/Deployments-499159]
```

**Comment by afscrome** [comment]
I was looking for having the link at the beginning so that you can click through to octopus for further details whilst a deployment is in progress - particularly useful when manual intervention steps are involved.

**Comment by johnsimons** [comment]
Thanks for the suggestion but we want to keep the knowledge of Portal urls in the Portal.
This would put a dependency on the OctopusClient knowing how the Portal structures urls.

I am going to close this issue for now, if you have any further information let us know.

**Comment by matt-richardson** [comment]
I'm keen for this - I happened to ask for it internally recently as well.
The response from the server would contain a "web" link pointing to the release, wouldn't it?
