### ISSUE TITLE
Feature Request: Add support for environment variable or config file settings for Octopus URL and API key

### ISSUE THREAD

**Issue by Draftkings** [OctopusDeploy/OctopusClients#225]
Hello,

While using the Octopus CLI to automate the actions of the Octopus deploy server, it would be great to have the ability to set environment variables or setup a config file in your user profile with the Octopus Server URL and API key. This information could then be omitted from all Octopus CLI command line actions.

**Comment by shaunmarx** [comment]
Hi @Draftkings, thanks for the suggestion this is a good idea. We will look into what we need to do to enable this.
