### ISSUE TITLE
Docker Image with Octo CLI Tool

### ISSUE THREAD

**Issue by RehanSaeed** [OctopusDeploy/OctopusClients#234]
I no longer want to ever install build tools on a CI server. I'd like to run the octo CLI tool from a Docker container instead. Please release a Docker container for this purpose. In particular, I'd like an Alpine or failing that a Ubuntu distribution of linux.

**Comment by slewis74** [comment]
Hi @RehanSaeed, thanks for your request. Docker support along these lines isn't something that's currently on our roadmap. This can be swayed by public opinion in [our UserVoice site](http://octopusdeploy.uservoice.com) though, so I'd recommend creating a suggestion over there is you feel strongly enough about it.
