### ISSUE TITLE
Octo pack ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by kvpt** [OctopusDeploy/OctopusClients#245]
Hi,

If a file contain an invalid LastWriteTime, the pack command fail with an ArgumentOutOfRange exception.
I encountered this issue with several node modules.

To create a file wich trigger this issue, you can execute this powershell command :
> (New-Item OutOfRange.txt).LastWriteTime = Get-Date -Date "1970-1-1"

Octo Pack on this file fail.

Currently we have to use a powershell script step in your build before the octopus step to set the LastWriteTime on all file with invalid date.

**Comment by mcasperson** [comment]
Hi @kvpt, thanks for reporting the issue.

Can you attach the exact error that is reported when a file with an invalid LastWriteTime is encountered?

**Comment by kvpt** [comment]
I use the VSTS task but the error is also present in the last executable version.

I cloned the project to catch the issue with the debugger.

![octopackissue](https://user-images.githubusercontent.com/1446221/38838003-93bffffc-41d4-11e8-8840-d74abd8fe8cd.PNG)

**Comment by mcasperson** [comment]
This will be fixed in version 4.32.1, which should go out in the next few days.
