### ISSUE TITLE
Add 'AzureServiceFabricCluster' to ConnectionStyle enum list

### ISSUE THREAD

**Issue by AdamDratwa** [OctopusDeploy/OctopusClients#261]
Hello, the new target type was introduced in 2018.5: https://octopus.com/docs/infrastructure/azure/service-fabric-cluster-targets
ConnectionStyle enum list does not contain a new type ('AzureServiceFabricCluster') which leads to exception while trying to parse response from /api/machines endpoints, while using all .Machines methods (if you have such deployment target created for your ServiceFabric projects of course).
Thanks, Adam

**Comment by Dalmirog** [comment]
Hi @AdamDratwa . We shipped version `4.36.1` of the client a couple of hours ago which should include a fix for this.
