### ISSUE TITLE
Octo.exe pack a .nuspec

### ISSUE THREAD

**Issue by BlythMeister** [OctopusDeploy/OctopusClients#330]
I have a lot of old nuspec files which we currently pack with an old version of the nuget.exe.

These aren't just .net projects, but could be other deployment packages.

Is there a way to get the octo.exe to pack these (preferably as zips)

I have hand rolled my own parser for nuspecs in my fake build script, but this feels like something octo.exe could support.

**Comment by mcasperson** [comment]
Hi Blyth, although octo.exe can be used to create a nupkg file, it does not read nuspec files to do so. So unfortunately there is no way for octo.exe to replace nuget.exe for projects with a nuspec files.

**Comment by BlythMeister** [comment]
@mcasperson this was more a feature request to support that mechism for packing either nupkg or zips from a file based definition.
With support for globbing the source and stating it's target location in the zip/package
