### ISSUE TITLE
Be able to exclude steps when deploying packages

### ISSUE THREAD

**Issue by nitrocode** [OctopusDeploy/OctopusClients#354]
There are cases where some projects have 4 steps and we need to only run one or all of the steps except one step. This can be done in the UI but not from the octo cli.

It would make it easier for us if we could do this via the CLI.

Thank you.

**Comment by slewis74** [comment]
Hi @nitrocode, thanks for getting in touch. The CLI supports this via the `--skip` parameter to the [`deploy-release`](https://octopus.com/docs/api-and-integration/octo.exe-command-line/deploy-release) command.
In the code the param handling starts [here](https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs#L47). 

You can specify this parameter multiple times to skip multiple steps.

**Comment by nitrocode** [comment]
@slewis74 thank you, I did not know you can skip commands with the name of the step. I just hit the opposite limitation too and wrote up the ticket here https://github.com/OctopusDeploy/OctopusClients/issues/357
