### ISSUE TITLE
Client side filtering is inefficient when running some octo.exe commands

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctopusClients#370]
https://secure.helpscout.net/conversation/752071654

The client code performs filtering on the client side, requiring all items from the server (releases, deployments etc) to be first downloaded from the server. This is inefficient when there are large numbers of items to be downloaded.

**Comment by johnsimons** [comment]
@mcasperson I can no longer access the link provided to help scout.
Is this still important to be worked on? Do you remember what commands were more problematic?

**Comment by mcasperson** [comment]
I don't recall to be honest, it was a few years ago now.

**Comment by johnsimons** [comment]
We are constantly making performance improvements to all our products.
If this is still an issue please let us know, but for now, I am closing this issue.

**Comment by JordoTheDev** [comment]
running `octo list-releases` still takes a very long time as noted here: https://help.octopus.com/t/octo-exe-list-releases-taking-unnecessarily-long-time/22067/2
