### ISSUE TITLE
Octo `6.32.` throw NullReferenceException when creating release

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/OctopusClients#417]
Octo.exe `6.3.2` throws an exception when connecting to a Octopus server version < `2018.8` to create a release.

In versions earlier than `2018.8` the package reference names are null, rather than blank, and the release plan code is only expecting non-null strings currently.

Source

https://help.octopus.com/t/in-azure-devops-the-create-octopus-release-fails-with-return-code-4294967293/22797

**Comment by christianfroehlich** [comment]
Hi @slewis74, we are eager for this fix as the bug is breaking our deployments. Do you know when this will be released?
