### ISSUE TITLE
Octo 6.8.0 - Push - String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by sstiglitz** [OctopusDeploy/OctopusClients#432]
### The Bug

Using Octo 6.8.0, we are getting the error `String was not recognized as a valid DateTime.` when pushing a new package.

### Expected

Running `Octo push "--server=https://OctopusServer/" "--apiKey=****" "--package=package.zip" --replace-existing` results in successful upload.

### Actual

Error occurs `Something went wrong while performing a delta transfer: Unable to process response from server: String 'Tuesday, June 18, 2019 8:34 PM' was not recognized as a valid DateTime.. Response content: {`

See log for full details.

### Details

Octopus version: 2018.9.9; API version: 3.0.0

Reviewing previous pipeline logs from yesterday, version 6.7.0 worked just fine. Additionally, I was able to manually push the package using the version currently published on your website, 6.2.3.

Log file: [log.txt](https://github.com/OctopusDeploy/OctopusClients/files/3304497/log.txt)

**Comment by AirEssY** [comment]
Also happening on 2018.11.2

**Comment by matt-richardson** [comment]
Thanks for letting us know - sorry to see this has caused you pain here.
I've delisted it from the downloads page - https://octopus.com/downloads/2019.5.10.

I presume you're finding this with some automation - can you let me know where you're downloading it from and I'll make sure it's delisted there too.

**Comment by sstiglitz** [comment]
Yes, it is automation. We have a scheduled release to our QA environments at 8pm PT nightly.

From our logs, it appears to be checking in at the endpoint https://g.octopushq.com. From there, it begins download from https://download.octopusdeploy.com. The mechanism to do this is the Octopus extension avilable on the marketplace. https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks

I just tried again and still picking up 6.8.0.

`
2019-06-19T06:46:20.1631669Z Attempting to contact https://g.octopushq.com to find latest CLI tools
2019-06-19T06:46:20.3235218Z Checking local tool cache
2019-06-19T06:46:20.3249666Z Attempting to download octo cli
2019-06-19T06:46:20.3301291Z Downloading: https://download.octopusdeploy.com/octopus-tools/6.8.0/OctopusTools.6.8.0.portable.zip
`

**Comment by sstiglitz** [comment]
Here I fumbled through the code in https://github.com/OctopusDeploy/OctoTFS/blob/master/source/tasks/Utils/install.ts

It's doing a GET to `https://g.octopushq.com/LatestTools` . Definitely still listing 6.8.0.

**Comment by adam-risberg** [comment]
We are having this issue as well. We have automated builds on Team Foundation Server which uses the "Push package(s) to Octopus" build task which fails with this error message. Temporarily downgrading the version of that task from 3.* to 2.* worked for us.

**Comment by kimkdk** [comment]
We have the same problem using the "Create Octopus Release" version 3.* task on Azure DevOps. Downgrading to 2.* solved it for now.

**Comment by andrstor** [comment]
Any hope of this getting fixed soon? Downgrading is not a very good solution for us as we have hundreds of builds that have this issue

**Comment by samjudson** [comment]
Hi

We are using the Octopus Deploy Push Packages task in Azure Devops and we are now seeing this issue as well.

I deleted the 6.8.0 tools from the agent directory, and on next run it downloaded it again:

> Attempting to contact https://g.octopushq.com to find latest CLI tools
> Checking local tool cache
> Attempting to download octo cli
> Downloading: https://download.octopusdeploy.com/octopus-tools/6.8.0/OctopusTools.6.8.0.portable.zip
> Extracting archive

We also have quite a few builds with this issue so I wouldn't like to have to downgrade them all. This version needs delisting from whatever end point the task is looking at, or the fix needs rolling out rather quickly.

**Comment by samjudson** [comment]
Also, we only recently migrate from one version of Azure DevOps to another so needed to reinstall all out custom tasks - we don't actually have 2.* version of Octopus tasks installed, so can't downgrade!

**Comment by zentron** [comment]
We have a fix for this in the works which will make the tool compatible with the older versions of Octopus server. Thanks for your patience with this issue.

**Comment by matt-richardson** [comment]
We’ve updated the file that says which version is latest to point to 6.7.0. I’m not sure if there’s any caching involved, but it should now start downloading the correct version. You may have to delete the cached file as mentioned by @samjudson.

**Comment by samjudson** [comment]
@matt-richardson There must be caching somewhere.

`https://g.octopushq.com/LatestTools` redirects to `https://download.octopusdeploy.com/octopus-tools/latest.json` which still contains 6.8.0 as the latest version.

As a hack I've manually gone to my agent tools directory and copied the 6.7.0 directory over the 6.8.0 directory.

e.g. `C:\BuildAgents\A1\_work\_tool\Octo\6.7.0` -> `C:\BuildAgents\A1\_work\_tool\Octo\6.8.0`

**Comment by matt-richardson** [comment]
Okay, `octo.exe` `6.8.1` has been released, which handles parsing package dates in a much better way.
Please give it a go, and let me know how it goes.

**Comment by matt-richardson** [comment]
Background: we fixed https://github.com/OctopusDeploy/Issues/issues/5535 in `2019.5.1`, which changed the api so that it returns an ISO date, rather than a "human readable" date. We paired this with a fix in OctopusClients (https://github.com/OctopusDeploy/OctopusClients/pull/429) to handle both old and new date formats, so we thought we were in a good spot.

Unfortunately, when it was implemented, it was missed that in `2019.2.0`, we shipped https://github.com/OctopusDeploy/Issues/issues/5006, which changed the date format to include timezones.

So, the change worked on `2019.2.0`+ servers, and unfortunately fell over on older servers.

The fix now also tries to parse the date using the system locale (on the assumption that the server and client _should_ be pretty similar in terms of locale) as well as the "long date format with timezone" and "iso date format" and if it cant parse it, it returns a null date, on the theory that this field isn't commonly used.

**Comment by richj** [comment]
How do we get this upgrade installed for TFS Builds?  The extension we have says it is current.  Our work directories all are pointing to 6.8.0 - is there a source for that somewhere we can change?

**Comment by Justin-Walsh** [comment]
Hi everyone,

Just a quick note to let you know that we had a few cache issues with Cloudflare earlier today, and it was holding on to a stale version of our "latest files" feed on some of their network. We've manually cleared these offending instances as of about an hour ago, so your build tasks should pull down 6.8.1 automatically (if they're not configured to install 6.7.0) now.
