### ISSUE TITLE
Update 'dotnet octo' tool for .NET 5

### ISSUE THREAD

**Issue by lsfera** [OctopusDeploy/OctopusClients#562]
I'm currently leveraging the tool in a /dotnet/sdk:5.0 container and unfortunately getting the following error ...
>It was not possible to find any compatible framework version
>The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
>  - The following frameworks were found:
>     5.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by lsfera** [comment]
Duplicate of https://github.com/OctopusDeploy/Issues/issues/6704

**Comment by millerjn21** [comment]
Duplicate as stated above. Closing this one and put both references in 6704.
