### ISSUE TITLE
Multiple client errors with 11.6.3644

### ISSUE THREAD

**Issue by cdhunt** [OctopusDeploy/OctopusClients#640]
We are seeing multiple issues with client builds that went out last night working with VCS projects.

CLI 7.4.3647
```
Unable to process response from server: Requested value 'Reference' was not found.
```

Octopus.Server.Client 11.6.3644

```
Newtonsoft.Json: Unable to find a constructor to use for type Octopus.Client.Model.DeploymentActionPackageResource. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'VersioningStrategy.DonorPackage.DeploymentAction', line 17, position 25.
```

**Comment by dylanlerch** [comment]
## JSON deserialisation error
This only appears to be an issue with the ILMerged version of the library (Octopus.Client). Can work around this one using [Octopus.Server.Client](https://www.nuget.org/packages/Octopus.Server.Client/).

We're still trying to get to the bottom of what caused this, but that's being tracked here: https://github.com/OctopusDeploy/OctopusClients/issues/642

## Requested value `Reference` was not found.
This was a combination of a few issues:

1. We added a new credential type for Git projects to support [shared configuration as code credentials](https://github.com/OctopusDeploy/Issues/issues/7342), and you need an updated client version to support this. This was added in `v11.3.3541`
2. We incorrectly published a build of [Octopus.DotNet.Cli](https://www.nuget.org/packages/Octopus.DotNet.Cli/) with a bad version number (3451.0.3458) a few months back, this was unlisted but the `dotnet` tool installer was still resolving it. _This old version didn't have support for the `Reference` credential type._
    - This package version deleted completely, so that won't be getting resolved anymore. More info here: https://github.com/OctopusDeploy/OctopusCLI/issues/162
    - This issue has been raised with the SDK team and they're looking into it: https://github.com/dotnet/sdk/issues/24037

**Comment by dylanlerch** [comment]
Closing this one out with these resolutions:

- **JSON deserialisation error**: This will no longer work with `Octopus.Client`, using `Octopus.Server.Client` will get you working again. Check out the full details about this (and a link to the updated documentation) in #642.
- **`Reference` was not found**: The bad version `3451.0.3458` has been removed from NuGet completely. If you use the latest version when installing through the dotnet CLI, you shouldn't see this error anymore.

Feel free to reopen this if you're still hitting any of these issues. 😄
