### ISSUE TITLE
Re-enable the `ignoreSslErrors` command line option

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/OctopusClients#86]
In `Octo.exe` 4.0 support for the `ignoreSslErrors` command line option was dropped due to `HttpClient` not supporting it. It will support it in `4.2.0`, so when that is released flip on the `HTTP_CLIENT_SUPPORTS_SSL_OPTIONS` compiler option to re-enable this feature.

Also check that `Octopus.Client.IgnoreServerCertificateCallback` logs to output correctly.

**Comment by PashCracken** [comment]
Hi,

Version 4.3.0 is out now. Any chance of enabling this again?

/Jan

**Comment by droyad** [comment]
@PashCracken I missed that, thanks for the heads up. I'll have a look into this today.

**Comment by droyad** [comment]
The option has been re-implemented for `Octo.exe` on all platforms. 

There is also an option to turn it on for the dotnet core build of `OctopusAsyncClient`.

The option isn't (and probably never will be) available on .NET 4.5 builds of `Octopus.Client` (and conversely `OctopusClient`) as in that world the SSL ignoring needs to be done Appdomain wide. See the [example](https://github.com/OctopusDeploy/OctopusClients/blob/cda2524e7e6ab26495949f64ab4ba1d1095a14c5/source/Octo/Commands/ApiCommand.cs#L219) to see how this can be done.
