### ISSUE TITLE
Async Client does support buffering or chunking on file upload

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/OctopusClients#96]
HttpClient doesn't support it, so this https://github.com/OctopusDeploy/OctopusClients/blob/3.5.4/source/Octopus.Client/OctopusClient.cs#L432 functionality was not added to the AsyncClient

**Comment by johnsimons** [comment]
@droyad I did some investigation on this issue.

The async client uses the `StreamContent` which will send the content as chunked depending on whether the length of the `Stream` is known (this is up to the consumer), see https://developercommunity.visualstudio.com/t/why-httpclient-always-transfer-encoding-chunked/878468#T-N909947

Regarding buffering, we currently do not specify a buffer size in [this](https://github.com/OctopusDeploy/OctopusClients/blob/e4c90722bd7c9cff24e775fe33cc5defc353b8c2/source/Octopus.Server.Client/OctopusAsyncClient.cs#L589) call, so by default, the buffer is set to `81920`. We can drop this number to be a smaller buffer size, but it cannot be `0`.

So @droyad, is there anything to do here?

**Comment by johnsimons** [comment]
Chatted with @droyad, happy to close
